import 'package:baseapp_getx/index.dart';

get sizedBox0 => const SizedBox.shrink();
get sizedBox4 => const SizedBox(width: 4, height: 4);
get sizedBox6 => const SizedBox(width: 6, height: 6);
get sizedBox8 => const SizedBox(width: 8, height: 8);
get sizedBox9 => const SizedBox(width: 9, height: 9);
get sizedBox10 => const SizedBox(width: 10, height: 10);
get sizedBox12 => const SizedBox(width: 12, height: 12);
get sizedBox16 => const SizedBox(width: 16, height: 16);
get sizedBox20 => const SizedBox(width: 20, height: 20);
get sizedBox24 => const SizedBox(width: 24, height: 24);
get sizedBox28 => const SizedBox(width: 28, height: 28);
get sizedBox30 => const SizedBox(width: 30, height: 30);
get sizedBox32 => const SizedBox(width: 32, height: 32);
get sizedBox36 => const SizedBox(width: 36, height: 36);
get sizedBox40 => const SizedBox(width: 40, height: 40);
get sizedBox44 => const SizedBox(width: 44, height: 44);
get sizedBox48 => const SizedBox(width: 48, height: 48);
get sizedBox64 => const SizedBox(width: 64, height: 64);
get sizedBox96 => const SizedBox(width: 96, height: 96);
get sizedBoxSafe => SizedBox(height: safeAreaBottom);
get sizedBox16safe => SizedBox(height: 16 + safeAreaBottom);
get sizedBox24safe => SizedBox(height: 24 + safeAreaBottom);
get filledBox16 => Container(color: WtColors.x__background, width: double.infinity, height: 16);
get filledBox24 => Container(color: WtColors.x__background, width: double.infinity, height: 24);
get filledBox32 => Container(color: WtColors.x__background, width: double.infinity, height: 32);
get filledBox40 => Container(color: WtColors.x__background, width: double.infinity, height: 40);
